base_url = "https://thamognya-hs-thai-blog.vercel.app/"
title = "HS Thai Lang and Society Blog"
description = "HS Thai language and Society Blog"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "visual-studio-dark"

[extra]
author = "Thamognya Kodi"
github = "Thamogny"
#twitter = "Thamognya"
